const ICONNAMES = [
    'oi oi-ban text-danger',
    'oi oi-bell text-danger',
    'oi oi-briefcase text-danger',
    'oi oi-bug text-danger',
    'oi oi-heart text-danger',
    'oi oi-camera-slr text-danger',
    'oi oi-cog text-danger',
    'oi oi-command text-danger',
    'oi oi-envelope-closed text-danger',
    'oi oi-headphones text-danger',
    'oi oi-heart text-danger',
    'oi oi-image text-danger',
    'oi oi-key text-danger',
    'oi oi-lock-locked text-danger',
    'oi oi-map-marker text-danger',
    'oi oi-medical-cross text-danger',
    'oi oi-microphone text-danger',
    'oi oi-moon text-danger',
    'oi oi-musical-note text-danger',
    'oi oi-phone text-danger',
    'oi oi-rain text-danger',
    'oi oi-rss text-danger',
    'oi oi-sun text-danger',
    'oi oi-shield text-danger',
    'oi oi-tablet text-danger',
    'oi oi-target text-danger',
    'oi oi-trash text-danger',
    'oi oi-volume-high text-danger',
    'oi oi-wifi text-danger',
    'oi oi-wrench text-danger',
    'oi oi-x text-danger'
    ];

module.exports = ICONNAMES;